apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: multi-trainer-
spec:
  entrypoint: main-dag
  templates:
    - name: main-dag
      dag:
        tasks:
          # Branche Parallele CPU : SVM, LogReg, XGBoost
          - name: train-cpu
            template: trainer-template
            arguments:
              parameters:
                - name: model_type
                  value: "{{item.type}}"
                - name: overrides
                  value: "{{item.overrides}}"
                - name: image
                  value: "inseefrlab/onyxia-vscode-python:py3.13.5"
            withItems:
              - { type: "svm", overrides: "model.svm.C=0.1,1.0,10.0" }
              - { type: "logreg", overrides: "model.logreg.C=0.1,1.0,10.0" }
              - { type: "xgboost", overrides: "model.xgboost.max_depth=3,6 model.xgboost.n_estimators=50,100,200" }

          # Branche Parallele GPU : Torch
          - name: train-gpu
            template: trainer-template
            arguments:
              parameters:
              - name: model_type
                value: "mlp"
              - name: overrides
                value: "model.mlp.lr=0.01,0.001 model.mlp.batch_size=32,64"
              - name: use_gpu
                value: "true"
              - name: image
                value: "inseefrlab/onyxia-vscode-pytorch:py3.13.5-gpu"

    - name: trainer-template
      inputs:
        parameters:
          - name: model_type
          - name: overrides
          - name: image
          - name: use_gpu
            value: "false"
      container:
        image: "{{inputs.parameters.image}}"
        imagePullPolicy: Always
        resources:
          # On definit les ressources dynamiquement
          limits:
            nvidia.com/gpu: "{{= inputs.parameters.use_gpu == 'true' ? 1 : 0 }}"
            cpu: "{{= inputs.parameters.use_gpu == 'true' ? '30000m' : '2000m' }}"
            memory: "{{= inputs.parameters.use_gpu == 'true' ? '50Gi' : '4Gi' }}"
          requests:
            nvidia.com/gpu: "{{= inputs.parameters.use_gpu == 'true' ? 1 : 0 }}"
            cpu: "50m"
            memory: "1Gi"
        command: ["/bin/bash", "-c"]
        args:
          - |
            set -e
            git clone -b main https://github.com/mateomorin/LabelGuard.git
            cd LabelGuard
            # On passe le model_type et les hyperparametres à Hydra
            # Le flag -m lance autant de runs MLFlow qu'il y a de configs dans 'overrides'
            uv run python -m src.training.trainer \
              model.type={{inputs.parameters.model_type}} \
              {{inputs.parameters.overrides}} \
              -m
        env:
          - name: MLFLOW_TRACKING_URI
            valueFrom: { secretKeyRef: { name: labelguard-train, key: MLFLOW_TRACKING_URI } }
          - name: MLFLOW_TRACKING_USERNAME
            valueFrom: { secretKeyRef: { name: labelguard-train, key: MLFLOW_TRACKING_USERNAME } }
          - name: MLFLOW_TRACKING_PASSWORD
            valueFrom: { secretKeyRef: { name: labelguard-train, key: MLFLOW_TRACKING_PASSWORD } }
          - name: QDRANT_API_KEY
            valueFrom: { secretKeyRef: { name: labelguard-train, key: QDRANT_API_KEY } }
