apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: multi-trainer-
spec:
  entrypoint: main-dag
  lifecycleEventConfig:
    handler: ""
  templates:
    - name: main-dag
      dag:
        tasks:
          # Branche Parallèle CPU : SVM, LogReg, XGBoost
          - name: train-cpu
            template: trainer-cpu
            arguments:
              parameters:
                - name: model_type
                  value: "{{item.type}}"
                - name: overrides
                  value: "{{item.overrides}}"
                - name: image
                  value: "inseefrlab/onyxia-vscode-python:py3.13.5"
            withItems:
              - { type: "svm", overrides: "model.svm.C=0.1,1.0,10.0" }
              - { type: "logreg", overrides: "model.logreg.C=0.1,1.0,10.0" }
              - { type: "xgboost", overrides: "model.xgboost.max_depth=3,6 model.xgboost.n_estimators=50,100,200" }

          # Branche Parallèle GPU : Torch
          - name: train-gpu
            template: trainer-gpu
            arguments:
              parameters:
                - name: model_type
                  value: "mlp"
                - name: overrides
                  value: '"({model.mlp.hidden_layers:[1024,256],model.mlp.dropout_layers:[0.3,0]},{model.mlp.hidden_layers:[1024,512,256],model.mlp.dropout_layers:[0.3,0.2,0]})"'
                - name: image
                  value: "inseefrlab/onyxia-vscode-pytorch:py3.13.5-gpu"

    # --- TEMPLATE CPU ---
    - name: trainer-cpu
      inputs:
        parameters:
          - name: model_type
          - name: overrides
          - name: image
      script:
        image: "{{inputs.parameters.image}}"
        imagePullPolicy: Always
        command: ["/bin/bash"]
        source: |
          set -e
          git clone -b main https://github.com/mateomorin/LabelGuard.git
          cd LabelGuard
          uv run python -m src.training.train qdrant.n_samples="all" \
            model.type={{inputs.parameters.model_type}} \
            {{inputs.parameters.overrides}} \
            -m
        resources:
          limits:
            cpu: "8000m"
            memory: "80Gi"
          requests:
            cpu: "4000m"
            memory: "64Gi"
        env: &common-env
          - name: MLFLOW_TRACKING_URI
            valueFrom: { secretKeyRef: { name: labelguard-train, key: MLFLOW_TRACKING_URI } }
          - name: MLFLOW_TRACKING_USERNAME
            valueFrom: { secretKeyRef: { name: labelguard-train, key: MLFLOW_TRACKING_USERNAME } }
          - name: MLFLOW_TRACKING_PASSWORD
            valueFrom: { secretKeyRef: { name: labelguard-train, key: MLFLOW_TRACKING_PASSWORD } }
          - name: QDRANT_API_KEY
            valueFrom: { secretKeyRef: { name: labelguard-train, key: QDRANT_API_KEY } }

    # --- TEMPLATE GPU ---
    - name: trainer-gpu
      inputs:
        parameters:
          - name: model_type
          - name: overrides
          - name: image
      script:
        image: "{{inputs.parameters.image}}"
        imagePullPolicy: Always
        command: ["/bin/bash"]
        source: |
          set -e
          git clone -b main https://github.com/mateomorin/LabelGuard.git
          cd LabelGuard
          uv run python -m src.training.train qdrant.n_samples="all" \
            model.type=mlp \
            model.mlp.lr=0.01,0.001 \
            model.mlp.hidden_layers="[1024,256]" \
            model.mlp.dropout_layers="[0.3,0]" \
            -m

          uv run python -m src.training.train qdrant.n_samples="all" \
            model.type=mlp \
            model.mlp.lr=0.01,0.001 \
            model.mlp.hidden_layers="[1024,512,256]" \
            model.mlp.dropout_layers="[0.3,0.2,0]" \
            -m
        resources:
          limits:
            nvidia.com/gpu: "1"
            cpu: "8000m"
            memory: "128Gi"
          requests:
            nvidia.com/gpu: "1"
            cpu: "4000m"
            memory: "64Gi"
        env: *common-env