random_state: 42

qdrant:
  original_collection: "original_cleaned"
  synth_collection: "naive_synth"
  collection_train: "train_v1"
  collection_test: "test_v1"
  n_samples: 5000

model:
  type: "mlp"
  logreg:
    C: 1
    solver: sag
    max_iter: 10000
  svm:
    C: 1
    max_iter: 100000
  mlp:
    input_dim: 4096
    hidden_layers: [1024, 256]
    dropout_layers: [0.3, 0]
    activation:
      _target_: torch.nn.ReLU
    lr: 0.001
    epochs: 20
    batch_size: 100
    patience: 3
  xgboost:
    n_estimators: 25
    learning_rate: 0.001
    max_depth: 2
    min_split_loss: 0
    subsample: 0.7
    colsample_bytree: 0.3

predictions:
  save_results: true
  train_path: null
  eval_path: null