random_state: 42

data:
  train_path: "s3://mateom/graal/embeddings/NAF2025/preprocessed/train.parquet"
  eval_path: "s3://mateom/graal/embeddings/NAF2025/preprocessed/eval.parquet"
  n_samples: "all"

model:
  name: mlp
  logreg:
    C: 1
    solver: sag
    max_iter: 10000
  svm:
    C: 1
    max_iter: 100000
  mlp:
    input_dim: 4096
    hidden_layers: [128, 32, 8]
    loss_fn:
      _target_: torch.nn.BCEWithLogitsLoss
    activation:
      _target_: torch.nn.ReLU
    lr: 0.001
    epochs: 10
    batch_size: 32
  xgboost:
    n_estimators: 5
    learning_rate: 0.001
    max_depth: 2
    min_split_loss: 0
    subsample: 0.7
    colsample_bytree: 0.3

predictions:
  save_results: true
  train_path: null
  eval_path: null