name: Run tests with uv

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      EMBEDDING_API_BASE_URL: ${{ secrets.EMBEDDING_API_BASE_URL }}
      EMBEDDING_API_KEY: ${{ secrets.EMBEDDING_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Verify uv
        run: uv --version

      - name: Install dependencies
        run: uv sync

      - name: Run data tests    # No data importation from s3 because timeout
        run: uv run pytest tests/datasets/test_data_preprocessing.py

      - name: Run embedding tests
        run : uv run pytest tests/test_embedders.py

      - name: Run model tests
        run : uv run pytest tests/test_models.py